using UnityEngine;

namespace Shadowfall
{
    /// <summary>
    /// One dungeon: where its entrance is and how it looks inside. Must match DUNGEONS in server/content.js
    /// (same order: the index is what client and server send each other). Layouts are generated by the server,
    /// fresh for every party.
    /// </summary>
    public class DungeonDef
    {
        public string Id, Name, Blurb, Boss;
        public Vector2 Design;          // entrance in design coordinates (see WorldGenerator.Map), or world coordinates if World
        public bool World;              // the outer lands' dungeons give their entrance in world coordinates
        public int Depths, MinLevel;
        // Look inside
        public string FloorTex, WallTex;
        public Color FloorTint, WallTint, TorchColor, BossFire;
        public string[] RoomProps;      // models scattered in rooms / clearings
        public bool Caves;

        public static readonly DungeonDef[] All =
        {
            new DungeonDef
            {
                Id = "catacombs", Name = "The Catacombs", Boss = "The Crypt Lord", Blurb = "Crypts under the graveyard. The Crypt Lord waits at the bottom.",
                Design = new Vector2(104.5f, 27.5f), Depths = 3, MinLevel = 6,
                FloorTex = "Ground/cobble", WallTex = "Ground/gravel", FloorTint = new Color(0.62f, 0.58f, 0.54f), WallTint = new Color(0.5f, 0.46f, 0.42f),
                TorchColor = new Color(1f, 0.6f, 0.28f), BossFire = new Color(1f, 0.3f, 0.15f),
                RoomProps = new[] { "Graveyard/coffin", "Graveyard/candle-multiple", "Graveyard/gravestone-broken", "Props/barrel_small_stack" },
            },
            new DungeonDef
            {
                Id = "hideout", Name = "Bandit Hideout", Boss = "The Bandit Lord", Blurb = "Cellars dug under the woods, full of stolen goods. Home of the Bandit Lord.",
                Design = new Vector2(104f, 132f), Depths = 2, MinLevel = 3,
                FloorTex = "Ground/dirt", WallTex = "Ground/forest", FloorTint = new Color(0.62f, 0.52f, 0.4f), WallTint = new Color(0.45f, 0.36f, 0.26f),
                TorchColor = new Color(1f, 0.7f, 0.35f), BossFire = new Color(1f, 0.5f, 0.2f),
                RoomProps = new[] { "Props/crates_stacked", "Props/barrel_large", "Props/box_stacked", "Nature/log_stack", "Props/chest" },
            },
            new DungeonDef
            {
                Id = "warrens", Name = "Goblin Warrens", Boss = "The Goblin King", Blurb = "Tunnels gnawed under the encampment. The Goblin King hoards there.",
                Design = new Vector2(138f, 74f), Depths = 3, MinLevel = 4, Caves = true,
                FloorTex = "Ground/dirt", WallTex = "Ground/dry", FloorTint = new Color(0.58f, 0.46f, 0.34f), WallTint = new Color(0.5f, 0.38f, 0.26f),
                TorchColor = new Color(1f, 0.55f, 0.2f), BossFire = new Color(0.9f, 0.6f, 0.1f),
                RoomProps = new[] { "Nature/tent_smallClosed", "Nature/campfire_stones", "Props/barrel_small_stack", "Plants/Mushrooms", "Nature/log_large" },
            },
            new DungeonDef
            {
                Id = "mine", Name = "Ironvein Deep", Boss = "The Stone Colossus", Blurb = "An abandoned mine where the golems woke up. Something huge moves at the bottom.",
                Design = new Vector2(26f, 96f), Depths = 3, MinLevel = 10, Caves = true,
                FloorTex = "Ground/gravel", WallTex = "Ground/gravel", FloorTint = new Color(0.5f, 0.52f, 0.56f), WallTint = new Color(0.38f, 0.4f, 0.46f),
                TorchColor = new Color(0.7f, 0.85f, 1f), BossFire = new Color(0.4f, 0.75f, 1f),
                RoomProps = new[] { "Rocks/Boulder_1", "Rocks/Boulder_3", "Town/cart", "Rocks/Pebble_2", "Props/crates_stacked" },
            },
            // ---- the outer lands
            new DungeonDef
            {
                Id = "barrow", Name = "The Frozen Barrow", Boss = "The Frost Witch", Blurb = "Ice caves under the Frostpeak pines, where the Frost Witch keeps the dead from thawing.",
                Design = new Vector2(210f, 428f), World = true, Depths = 3, MinLevel = 15, Caves = true,
                FloorTex = "Ground/gravel", WallTex = "Ground/gravel", FloorTint = new Color(0.7f, 0.78f, 0.88f), WallTint = new Color(0.62f, 0.72f, 0.85f),
                TorchColor = new Color(0.55f, 0.85f, 1f), BossFire = new Color(0.45f, 0.8f, 1f),
                RoomProps = new[] { "Rocks/Boulder_2", "Rocks/Pebble_1", "Graveyard/coffin", "Nature/log_large", "Graveyard/gravestone-broken" },
            },
            new DungeonDef
            {
                Id = "temple", Name = "The Sunken Temple", Boss = "The Sand Colossus", Blurb = "A sun temple the dunes swallowed. Raiders loot its halls; something older guards the altar.",
                Design = new Vector2(470f, 236f), World = true, Depths = 3, MinLevel = 16,
                FloorTex = "Ground/sand", WallTex = "Ground/dry", FloorTint = new Color(0.85f, 0.75f, 0.55f), WallTint = new Color(0.7f, 0.58f, 0.4f),
                TorchColor = new Color(1f, 0.75f, 0.35f), BossFire = new Color(1f, 0.65f, 0.2f),
                RoomProps = new[] { "Graveyard/pillar-large", "Props/chest", "Rocks/Pebble_3", "Graveyard/stone-wall-column", "Props/barrel_large" },
            },
            new DungeonDef
            {
                Id = "citadel", Name = "The Ashen Citadel", Boss = "The Cinder Lord", Blurb = "The fortress the Reach burned down around. Its lord is still in there, and still burning.",
                Design = new Vector2(400f, 502f), World = true, Depths = 3, MinLevel = 20,
                FloorTex = "Ground/cobble", WallTex = "Ground/gravel", FloorTint = new Color(0.45f, 0.4f, 0.4f), WallTint = new Color(0.4f, 0.32f, 0.3f),
                TorchColor = new Color(1f, 0.45f, 0.2f), BossFire = new Color(1f, 0.3f, 0.1f),
                RoomProps = new[] { "Graveyard/coffin", "Graveyard/gravestone-broken", "Graveyard/stone-wall-column", "Graveyard/candle-multiple", "Graveyard/trunk" },
            },
        };

        public static DungeonDef Get(int index) => All[Mathf.Clamp(index, 0, All.Length - 1)];

        /// <summary>
        /// The entrance: the design position moved to the nearest spot with a clear 5x5 area. The server runs the
        /// identical search (resolveEntrance in server.js) on the identical map, so both always agree.
        /// </summary>
        public Vector3 Entrance
        {
            get
            {
                if (entrance.HasValue) return entrance.Value;
                var grid = WorldGrid.Instance;
                int cx = Mathf.FloorToInt(World ? Design.x : WorldGenerator.Map(Design.x)), cz = Mathf.FloorToInt(World ? Design.y : WorldGenerator.Map(Design.y));
                bool Clear(int px, int pz)
                {
                    for (int j = -2; j <= 2; j++)
                        for (int i = -2; i <= 2; i++)
                            if (grid.IsBlocked(px + i, pz + j)) return false;
                    return true;
                }
                for (int r = 0; r <= 30; r++)
                    for (int dz = -r; dz <= r; dz++)
                        for (int dx = -r; dx <= r; dx++)
                        {
                            if (Mathf.Max(Mathf.Abs(dx), Mathf.Abs(dz)) != r) continue;
                            if (Clear(cx + dx, cz + dz)) { entrance = new Vector3(cx + dx + 0.5f, 0f, cz + dz + 0.5f); return entrance.Value; }
                        }
                entrance = new Vector3(cx + 0.5f, 0f, cz + 0.5f);
                return entrance.Value;
            }
        }
        Vector3? entrance;
    }

    /// <summary>The way into a dungeon: each one has its own look (crypt, trapdoor shack, cave mouth, mine adit).</summary>
    public class DungeonEntrance : Interactable
    {
        public int Index;
        public DungeonDef Def => DungeonDef.Get(Index);

        public override Color LabelColor => new Color(1f, 0.55f, 0.3f);
        public override float LabelHeight => 3.6f;
        public override string HoverText => Def.Name + "\n<dungeon, level " + Def.MinLevel + "+>";

        public static void SpawnAll()
        {
            for (int i = 0; i < DungeonDef.All.Length; i++) Spawn(i);
        }

        static void Spawn(int index)
        {
            var def = DungeonDef.Get(index);
            var pos = def.Entrance;
            var go = new GameObject("Entrance " + def.Name);
            go.transform.position = pos;
            var e = go.AddComponent<DungeonEntrance>();
            e.Index = index;
            e.DisplayName = def.Name;
            e.InteractRange = 2.5f;
            e.AddClickCollider(1.2f, 3f);
            var t = go.transform;
            Color glow = def.TorchColor;
            switch (def.Id)
            {
                case "catacombs":
                    ArtLibrary.Spawn("Graveyard/crypt", t, new Vector3(0f, 0f, 2.2f), 4.2f, ArtLibrary.Fit.Width, 180f);
                    break;
                case "hideout":
                    // A ruined woodcutter's shack with a trapdoor, logs and crates.
                    ArtLibrary.Spawn("Buildings/building_home_A_green", t, new Vector3(0f, 0f, 2.6f), 3.6f, ArtLibrary.Fit.Width, 180f);
                    ArtLibrary.Spawn("Nature/log_stack", t, new Vector3(-2.2f, 0f, 0.4f), 1.2f, ArtLibrary.Fit.Height, 30f);
                    ArtLibrary.Spawn("Props/crates_stacked", t, new Vector3(2.1f, 0f, 0.6f), 1.2f, ArtLibrary.Fit.Height, -20f);
                    Factory.Prim(PrimitiveType.Cube, t, new Vector3(0f, 0.03f, 0.2f), new Vector3(1.6f, 0.06f, 1.6f), new Color(0.25f, 0.17f, 0.1f));
                    break;
                case "warrens":
                    // A cave mouth ringed with boulders and a goblin banner.
                    ArtLibrary.Spawn("Rocks/Boulder_1", t, new Vector3(-2.2f, 0f, 1.6f), 3.2f, ArtLibrary.Fit.Width, 0f);
                    ArtLibrary.Spawn("Rocks/Boulder_2", t, new Vector3(2.2f, 0f, 1.6f), 3.2f, ArtLibrary.Fit.Width, 90f);
                    ArtLibrary.Spawn("Rocks/Boulder_3", t, new Vector3(0f, 0f, 2.8f), 3.2f, ArtLibrary.Fit.Height, 0f);
                    ArtLibrary.Spawn("Town/banner-red", t, new Vector3(-1.6f, 0f, -0.4f), 2.6f, ArtLibrary.Fit.Height, 0f);
                    Factory.Prim(PrimitiveType.Cylinder, t, new Vector3(0f, 0.02f, 0.6f), new Vector3(2.2f, 0.02f, 1.6f), new Color(0.03f, 0.02f, 0.02f));
                    break;
                case "barrow":
                    // A barrow mound of frosted boulders around a crypt door.
                    ArtLibrary.Spawn("Graveyard/crypt", t, new Vector3(0f, 0f, 2.2f), 4f, ArtLibrary.Fit.Width, 180f);
                    ArtLibrary.Spawn("Rocks/Boulder_1", t, new Vector3(-2.8f, 0f, 2.4f), 3f, ArtLibrary.Fit.Width, 0f);
                    ArtLibrary.Spawn("Rocks/Boulder_2", t, new Vector3(2.8f, 0f, 2.4f), 3f, ArtLibrary.Fit.Width, 120f);
                    ArtLibrary.Spawn("Graveyard/gravestone-broken", t, new Vector3(-1.8f, 0f, -0.6f), 1.2f, ArtLibrary.Fit.Height, 20f);
                    break;
                case "temple":
                    // Two pillars and a broken lintel sticking out of the sand.
                    ArtLibrary.Spawn("Graveyard/pillar-large", t, new Vector3(-1.5f, 0f, 1.4f), 3.4f, ArtLibrary.Fit.Height, 0f);
                    ArtLibrary.Spawn("Graveyard/pillar-large", t, new Vector3(1.5f, 0f, 1.4f), 2.6f, ArtLibrary.Fit.Height, 0f);
                    Factory.Prim(PrimitiveType.Cube, t, new Vector3(-0.3f, 3.1f, 1.4f), new Vector3(3.2f, 0.4f, 0.6f), new Color(0.7f, 0.6f, 0.42f))
                        .transform.localRotation = Quaternion.Euler(0f, 0f, -8f);
                    ArtLibrary.Spawn("Graveyard/stone-wall-column", t, new Vector3(2.8f, 0f, 0.2f), 1.6f, ArtLibrary.Fit.Height, 30f);
                    Factory.Prim(PrimitiveType.Cube, t, new Vector3(0f, 1.1f, 1.6f), new Vector3(2.2f, 2.2f, 0.1f), new Color(0.03f, 0.02f, 0.02f));
                    break;
                case "citadel":
                    // A gatehouse of black stone flanked by fire baskets.
                    ArtLibrary.Spawn("Graveyard/crypt-large", t, new Vector3(0f, 0f, 2.6f), 5f, ArtLibrary.Fit.Width, 180f);
                    ArtLibrary.Spawn("Graveyard/fire-basket", t, new Vector3(-2.4f, 0f, 0.4f), 1.4f, ArtLibrary.Fit.Height, 0f);
                    ArtLibrary.Spawn("Graveyard/fire-basket", t, new Vector3(2.4f, 0f, 0.4f), 1.4f, ArtLibrary.Fit.Height, 0f);
                    break;
                default:
                    // A timbered mine adit with a cart.
                    ArtLibrary.Spawn("Rocks/Boulder_3", t, new Vector3(-2.3f, 0f, 1.8f), 3.4f, ArtLibrary.Fit.Width, 0f);
                    ArtLibrary.Spawn("Rocks/Boulder_2", t, new Vector3(2.3f, 0f, 1.8f), 3.4f, ArtLibrary.Fit.Width, 0f);
                    ArtLibrary.Spawn("Town/pillar-wood", t, new Vector3(-1.1f, 0f, 1.2f), 2.6f, ArtLibrary.Fit.Height, 0f);
                    ArtLibrary.Spawn("Town/pillar-wood", t, new Vector3(1.1f, 0f, 1.2f), 2.6f, ArtLibrary.Fit.Height, 0f);
                    Factory.Prim(PrimitiveType.Cube, t, new Vector3(0f, 2.55f, 1.2f), new Vector3(2.8f, 0.3f, 0.35f), new Color(0.35f, 0.24f, 0.14f));
                    ArtLibrary.Spawn("Town/cart", t, new Vector3(2.4f, 0f, -0.6f), 1.8f, ArtLibrary.Fit.Width, 70f);
                    Factory.Prim(PrimitiveType.Cube, t, new Vector3(0f, 1.1f, 1.6f), new Vector3(1.9f, 2.2f, 0.1f), new Color(0.02f, 0.02f, 0.02f));
                    break;
            }
            SpellFx.Emit(new SpellFx.P
            {
                Rate = 25, Duration = 100000f, Life = new Vector2(1.2f, 2f), Speed = new Vector2(0.05f, 0.2f),
                Size = new Vector2(0.08f, 0.18f), Start = Color.Lerp(glow, Color.white, 0.3f), End = new Color(glow.r * 0.8f, glow.g * 0.4f, glow.b * 0.2f, 0f),
                Shape = ParticleSystemShapeType.Circle, Radius = 1f, Velocity = new Vector3(0f, 0.8f, 0f),
            }, pos + Vector3.up * 0.1f, go.transform);
            var l = new GameObject("EntranceLight").AddComponent<Light>();
            l.transform.SetParent(go.transform, false);
            l.transform.localPosition = new Vector3(0f, 1.6f, 0.6f);
            l.type = LightType.Point;
            l.color = glow;
            l.range = 7f;
            l.intensity = 2f;
            l.gameObject.AddComponent<Flicker>();
        }

        public override void Interact(Player p)
        {
            if (p.Level < Def.MinLevel)
                GameUI.Log(Def.Name + " is dangerous below level " + Def.MinLevel + ". Bring friends.", new Color(1f, 0.6f, 0.4f));
            GameUI.I?.ChooseDifficulty(Index);
        }
    }
}
